config-version: 1.2
global:
  prefix: " &8&l» "
  server-type: "" #LOBBY, REGISTRO, SKY_WARS, LOBBY_BED_WARS, BED_WARS, TNT_TAG, PRACTICE, SURVIVAL
  proxy-server-name: ""
  debug: true
spawn:
  location:
socket:
  ip: 172.18.0.1
  port: 5555

web:
  enabled: false
  uuid: null
  key: ASDJ209KASDHKADJ2KASDJGHASDK4KAHSKKDHGHJA8JA20LASDHGKALSKVMXJNASDOJG
  url: "http://209.222.97.163:3000"
  pluginsToDelete: [ ]
db:
  enabled: true
  host: 172.18.0.1
  port: 27017
  user: yandere
  password: JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK
  database: yandere
  urli: "mongodb://yandere:JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK@172.18.0.1:27017/"
commands-hidden:
  - "?"
  - "about"
  - "plugins"
  - "pl"
  - "ver"
  - "version"
  - "icanhasbukkit"
  - "worldedit"
  - "fawe"
  - "fawecancel"
  - "velocity"
  - "anvil"
  - ";"
  - "we"
  - "brush"
  - "vis"
  - "visual"
  - "visualize"
commands-hidden-starts-with:
  - "//"
  - "/bukkit"
  - "/worldedit"
  - "/luckperms"
  - "/placeholderapi"
  - "/jumppads"
  - "/fastasyncworldedit"
  - "/holographicdisplays"
