name: YandereCore
version: '${project.version}'
main: com.podcrash.commissions.yandere.core.spigot.Main
depend:
  - LuckPerms
softdepend:
  - StrikePractice
  - UltraSkyWars
  - UltraSkyWarsWP
  - BedWarsProxy
  - Parties

load: POSTWORLD
api-version: 1.13
