global:
  debug: true
web:
  enabled: false
  uuid: null
  key: ASDJ209KASDHKADJ2KASDJGHASDK4KAHSKKDHGHJA8JA20LASDHGKALSKVMXJNASDOJG
  url: "http://209.222.97.163:3000"
  pluginsToDelete: [ ]
db:
  enabled: true
  host: 172.18.0.1
  port: 27017
  user: yandere
  password: JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK
  database: yandere
  urli: "mongodb://yandere:JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK@172.18.0.1:27017/"

announcements:
  delay: 15
  list:
    1:
      timeType: MINUTES
      delay: 30
      sound: true
      messages:
        - "&7&m---------------&e&l Yandere &c&lRangos &7&m---------------"
        - ""
        - "&f   Compra rangos para obtener mejoras visuales, mayor"
        - "&f   prioridad, partículas, y mucho más dentro de nuestras"
        - "&f   diferentes modalidades."
        - ""
        - "    &e¡Compra tu rango en &c&ltienda.yanderecraft.com&f!"
        - ""
        - "&7&m------------------------------------------------"
    2:
      timeType: MINUTES
      delay: 30
      sound: true
      messages:
        - "&7&m---------------&e&l Yandere &c&lFiestas &7&m---------------"
        - ""
        - "&f               ¿Estás jugando con amigos?"
        - ""
        - "&f   Juega junto con ellos y muévete a través del server"
        - "&f   invitándolos a una &eFiesta &fcon el siguiente comando:"
        - ""
        - "&f                 &c/fiesta invite <amigo>."
        - ""
        - "&7&m------------------------------------------------"
