global:
  debug: true
web:
  uuid: null
  key: ASDJ209KASDHKADJ2KASDJGHASDK4KAHSKKDHGHJA8JA20LASDHGKALSKVMXJNASDOJG
  url: "http://209.222.97.163:3000"
  pluginsToDelete: [ ]
db:
  enabled: true
  host: 172.18.0.1
  port: 27017
  user: yandere
  password: JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK
  database: yandere
  urli: "mongodb://yandere:JF993KKLALLDJJ2KLALLGJASKJ29I9ASDK@172.18.0.1:27017/"